### ISSUE TITLE
Using triple quotes instead of single quotes with lmql>=0.0.6.1 

### ISSUE THREAD

**Issue by ruflair** [eth-sri/lmql#64]
Consider the following code:

```python
import asyncio

import lmql


@lmql.query
async def write_catch_phrase1(adj: str, noun: str):
    '''
    argmax "Write a catchphrase for the following company: {adj} {noun}. [catchphrase]" from "chatgpt"
    '''


@lmql.query
async def write_catch_phrase2(adj: str, noun: str):
    '''
    argmax
    """
        Write a catchphrase for the following company: {adj} {noun}. [catchphrase]
    """
    from "chatgpt"
    '''


async def main():
    catchphrase1 = (await write_catch_phrase1("colorful", "socks"))[0].variables["catchphrase"]
    print(catchphrase1)
    catchphrase2 = (await write_catch_phrase2("colorful", "socks"))[0].variables["catchphrase"]
    print(catchphrase2)


asyncio.run(main())

```

The function `write_catch_phrase1` (using single quotes) works with lmql==0.0.5.1 and lmql==0.0.6.1, while the second function `write_catch_phrase2` works only with lmql==0.0.5.1. The issue persists when using the functions as chains in langchain chains.
The error I get is: `AttributeError: 'LMQLTokenizer' object has no attribute 'vocab_range'. Did you mean: 'vocab_size'?`

**Comment by lbeurerkellner** [comment]
Thanks for reporting this. This is a cache invalidation issue (delete `~/.cache/lmql`) and is resolved in the recently released `0.0.6.3`.
