### ISSUE TITLE
AttributeError: 'LMQLTokenizer' object has no attribute 'vocab_range'

### ISSUE THREAD

**Issue by CircArgs** [eth-sri/lmql#67]
I have a query working with `0.0.5.1` (using the tiktoken branch) but with `0.0.6.0/1` I get the error:
`AttributeError: 'LMQLTokenizer' object has no attribute 'vocab_range'`

The query is very large automatically generated from a schema. I will add if requested, but I do not have an MVP yet.

**Comment by lbeurerkellner** [comment]
Hi there, this is a known issue with cache invalidation. Try to delete `~/.cache/lmql` to fix it. We are shipping an update today, which will handle automatic cache invalidation and cache versioning automatically. So this should not happen again.

**Comment by lbeurerkellner** [comment]
We just released 0.0.6.3, which should resolve the issue automatically. Going back to the `tiktoken` branch though, may require manual deletion of `~/.cache/lmql`.

**Comment by CircArgs** [comment]
@lbeurerkellner thanks for the help!
